### ISSUE TITLE
amethyst shard drop on punch

### ISSUE THREAD

**Issue by ink0stain4** [SFort/MC-invisframes#4] opened 2021-07-05 16:34 UTC
![issue](https://user-images.githubusercontent.com/86976806/124500026-5f978b00-de02-11eb-9eaf-c57cc2f8c15b.png)

 As depicted, the normal function of shift+punching the frame works, but it spits out particle effects and an amethyst shard along with the chime sound effect. I can't really imagine why this is happening, but if no one else is experiencing this, it must be just a weird mod conflict as I have many installed. I opened this issue incase this was of any interest to you, not so much that it was a problem strictly on your part.

**Comment by SFort** [comment] 2021-07-05 16:43
conflict, it can probably be easily resolved by just giving invisframes a higher priority. i would like to know whats causing it though just to make sure

**Comment by SFort** [comment] 2021-07-05 16:56
so i at least need a mod list / modpack name
if you don't know what mod is causing it

(also you can shift-punch item frames before putting in the item)

**Comment by ink0stain4** [comment] 2021-07-06 04:11
sure thing, I apologise though as there are 86 other mods installed, though
I'm sure more than a few can be ignored for this matter.

Tell me if there's anything else i can share
(version 1.17)
https://drive.google.com/drive/folders/1KhOuImUfxC79KLsG63inVX_FY33a29HX?usp=sharing

**Comment by SFort** [comment] 2021-07-06 04:19
ye that weas easy to find conflict with charm

**Comment by SFort** [comment] 2021-07-06 04:37
there's no way this can be fixed by me it is compleatly caused by charm.
it assumes it's the [only thing that can set entities invisable ](https://github.com/svenhjol/Charm/blob/5f454874683710a504317423b50016f46c991130/src/main/java/svenhjol/charm/module/clear_item_frames/ClearItemFrames.java#L73) 
as several mods and even vanilla do that,
so this is flat out just a item generation bug caused by charm
(made easier by invis frames)

sorry theres nothing i can do you should open a issue on [their bugtracker](https://github.com/svenhjol/Charm/issues)

**Closed as completed by SFort** 2021-07-06 04:37 UTC

**Comment by ink0stain4** [comment] 2021-07-06 05:10
thank you very much for getting back to me on this, I'll definitely report
the issue to them.
